language: java
sudo: required
jdk:
  - oraclejdk8
before_install:
- git clone --depth 1 https://github.com/Cooperate-Project/BuildUtils.git /tmp/BuildUtils
- . /tmp/BuildUtils/travisci/setup.sh
install: true
script:
- mavenBuild.sh
cache:
  directories:
  - "$HOME/.m2/repository"
env:
  global:  
  - secure: "czHypDKowG/gHon5KyMv0YbXd8hGwq4vV355geYhKNcriSDCv82YngJVZxF26K754b/+ZW80TMfIHIa2u1/eg8dL9BOn6FfVYdEUU3ndXEvyx3Kv6cJckkxWvjTfX4ExzejsA7ZfQMHHaQdIRnuDw6hfASjaQdF56ev2IzPQw10ha1GfrMhqbBBQyZjt7/GbWZ3Aw2RWpPQPrib5BjqKqftr9SXsocKvTkmt9Pb2UOW7RZuFTwbnr3zlnN9S2Tjjj2SeOJYTcnf45tr2gwvzGm817n4kbq+9NVcOIx5wgZqKw4M0vJhJ+R+G8Mbei00OqqO2jDiDjn0P2aUQp3PJRUChb8G4NE+IGR1S+SxDZHX+9v93efuO4qrS754EDjxlgThJlVVsvGiyNbbXQgQ85czq7XQTyVS7o4sIvCgBF8GtZPAz8b9609mcBMdooLVj86qCIgXy4HibYSoEDY9sRjcmm3cpcubNA8yy75ywPPzbuGo2rTHvSZb9r0yR7vI3X0H9UodS/TgVXfDrZen9DTGfFQVxtVNZJ2aoQsgvlLrGbYBrIhidX+4wlxnxeO7Ahhvv3Ch9/EWMadi57MfGsXzyug6fLQ/MjOg/6FjRvVrzU03BWBIwS3XWyp4qh0NS5ucsXEhWe0F2F2xT6suyw9QcL9ZqHoHm6+h+l3bPFD4="